### ISSUE TITLE
This seems fun and cool can you please offer some input recipies?

### ISSUE THREAD

**Issue by gschian0** [davidaramant/buddhabrot#1]
I would love some example commands.

Thanks!

**Comment by davidaramant** [comment]
This project is far from complete so there's not much to run yet. I'm still working on the first phase, which is a program to find the border of the Mandelbrot set.

I made an earlier 64 gigapixel version of the Buddhabrot which [I blogged about](https://davidaramant.github.io) if you're curious (sadly that rendering is not currently available online). My goal this time is 4 terapixels but I don't know yet if that's feasible :)
